name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: deployment-type
    attributes:
      label: Deployment Type
      description: How are you running WhisperS2T?
      options:
        - Proxmox LXC Container (Ubuntu 22.04)
        - Proxmox LXC Container (Debian 12)
        - Docker Container
        - Manual Installation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide system information
      placeholder: |
        - OS: Ubuntu 22.04
        - Container: LXC
        - CPU: 2 cores
        - RAM: 4GB
        - Whisper Model: base
      value: |
        - OS: 
        - Container: 
        - CPU: 
        - RAM: 
        - Whisper Model: 
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: |
        # Service logs
        journalctl -u whisper-appliance -n 50

        # Health check
        curl http://localhost:5000/health

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues
          required: true
        - label: I have tested with a fresh container installation
          required: false
        - label: I have included relevant logs
          required: false